import { Level, Song, UserProgress } from './types';

export const sampleLevels: Level[] = [
  {
    id: 'lvl-0a-teoria-fundamentos',
    title: 'curriculum.lvl0Teoria.title',
    subtitle: 'curriculum.lvl0Teoria.subtitle',
    role: 'fundamentos',
    steps: [
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Antes de empezar',
        instructionText:
          'El Do central (C4) es el Do más cercano al centro del teclado — normalmente justo debajo del logo del fabricante. Es el punto de referencia de todo el método: casi todo lo que aprendas parte de ahí.',
        illustration: { kind: 'keyboard', highlightNotes: ['C4'], markMiddleC: true },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Posición de la mano',
        instructionText:
          'Coloca la mano derecha sobre las 5 teclas blancas a partir del Do central, con los dedos curvados y relajados. Cada dedo tiene un número: 1 = pulgar, 2 = índice, 3 = medio, 4 = anular, 5 = meñique.',
        illustration: { kind: 'hand', side: 'right' },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Dos formas de nombrar las notas',
        instructionText:
          'En español usamos Do-Re-Mi-Fa-Sol-La-Si. En inglés (y en la notación que verás en apps y partituras) se usan letras: Do=C, Re=D, Mi=E, Fa=F, Sol=G, La=A, Si=B. Son la misma nota — dos nombres distintos. Aquí vas a ver ambos juntos, así te acostumbras a los dos.',
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Un poco más lejos: La y Si',
        instructionText:
          'Después de las 5 notas de la posición básica (Do a Sol), La (A) y Si (B) quedan justo a continuación. Todavía no te preocupes por qué dedo usar — solo identifica dónde están, ya vendrá la digitación más adelante.',
        illustration: { kind: 'keyboard', highlightNotes: ['A4', 'B4'] },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Ahora la mano izquierda',
        instructionText:
          'La mano izquierda se coloca una octava más abajo. El meñique (5) va en el Do grave, y el pulgar (1) queda en el Sol más cercano al Do central — los dos pulgares casi se tocan en el medio del teclado.',
        illustration: { kind: 'hand', side: 'left' },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'También hay La y Si graves',
        instructionText:
          'Igual que con la derecha, sigue contando hacia la derecha desde el Sol grave para encontrar La y Si.',
        illustration: { kind: 'keyboard', highlightNotes: ['A3', 'B3'] },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Lo que viene: práctica',
        instructionText:
          'Ya viste todo lo que necesitas. En el siguiente nivel practicas identificando estas notas con las dos manos — sin más explicaciones de por medio, para que puedas repetirlo las veces que quieras sin releer la teoría.',
      },
    ],
  },
  {
    id: 'lvl-0b-practica-fundamentos',
    title: 'curriculum.lvl0Practica.title',
    subtitle: 'curriculum.lvl0Practica.subtitle',
    role: 'fundamentos',
    steps: [
      {
        kind: 'note',
        expectedNotes: ['C4'],
        instructionText: 'Toca Do (C) con el pulgar',
        displayName: 'Do',
        fingerNumber: 1,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['D4'],
        instructionText: 'Toca Re (D) con el índice',
        displayName: 'Re',
        fingerNumber: 2,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['E4'],
        instructionText: 'Toca Mi (E) con el dedo medio',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['F4'],
        instructionText: 'Toca Fa (F) con el anular',
        displayName: 'Fa',
        fingerNumber: 4,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['G4'],
        instructionText: 'Toca Sol (G) con el meñique',
        displayName: 'Sol',
        fingerNumber: 5,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['E4'],
        instructionText: 'Identifica: Mi (E)',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['C4'],
        instructionText: 'Identifica: Do (C) central',
        displayName: 'Do',
        fingerNumber: 1,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['G4'],
        instructionText: 'Identifica: Sol (G)',
        displayName: 'Sol',
        fingerNumber: 5,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['D4'],
        instructionText: 'Identifica: Re (D)',
        displayName: 'Re',
        fingerNumber: 2,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['F4'],
        instructionText: 'Identifica: Fa (F)',
        displayName: 'Fa',
        fingerNumber: 4,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['A4'],
        instructionText: 'Toca La (A), justo después de Sol',
        displayName: 'La',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['B4'],
        instructionText: 'Toca Si (B), justo después de La',
        displayName: 'Si',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['A4'],
        instructionText: 'Identifica: La (A)',
        displayName: 'La',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['C4'],
        instructionText: 'Identifica: Do (C) central',
        displayName: 'Do',
        fingerNumber: 1,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['B4'],
        instructionText: 'Identifica: Si (B)',
        displayName: 'Si',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['E4'],
        instructionText: 'Identifica: Mi (E)',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['C3'],
        instructionText: 'Toca Do grave (C) con el meñique izquierdo',
        displayName: 'Do',
        fingerNumber: 5,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['D3'],
        instructionText: 'Toca Re (D) con el anular izquierdo',
        displayName: 'Re',
        fingerNumber: 4,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['E3'],
        instructionText: 'Toca Mi (E) con el dedo medio izquierdo',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['F3'],
        instructionText: 'Toca Fa (F) con el índice izquierdo',
        displayName: 'Fa',
        fingerNumber: 2,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['G3'],
        instructionText: 'Toca Sol (G) con el pulgar izquierdo',
        displayName: 'Sol',
        fingerNumber: 1,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['E3'],
        instructionText: 'Identifica con la izquierda: Mi (E)',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['C3'],
        instructionText: 'Identifica con la izquierda: Do (C) grave',
        displayName: 'Do',
        fingerNumber: 5,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['F3'],
        instructionText: 'Identifica con la izquierda: Fa (F)',
        displayName: 'Fa',
        fingerNumber: 2,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['A3'],
        instructionText: 'Toca La grave (A)',
        displayName: 'La',
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['B3'],
        instructionText: 'Toca Si grave (B)',
        displayName: 'Si',
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['G3'],
        instructionText: 'Identifica con la izquierda: Sol (G)',
        displayName: 'Sol',
        fingerNumber: 1,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['B3'],
        instructionText: 'Identifica con la izquierda: Si (B)',
        displayName: 'Si',
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['D3'],
        instructionText: 'Identifica con la izquierda: Re (D)',
        displayName: 'Re',
        fingerNumber: 4,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['A3'],
        instructionText: 'Identifica con la izquierda: La (A)',
        displayName: 'La',
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['C4'],
        instructionText: 'Repaso mezclado — identifica: Do (C) central',
        displayName: 'Do',
        fingerNumber: 1,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['G3'],
        instructionText: 'Repaso mezclado — identifica con la izquierda: Sol (G)',
        displayName: 'Sol',
        fingerNumber: 1,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['E4'],
        instructionText: 'Repaso mezclado — identifica: Mi (E)',
        displayName: 'Mi',
        fingerNumber: 3,
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['C3'],
        instructionText: 'Repaso mezclado — identifica con la izquierda: Do (C) grave',
        displayName: 'Do',
        fingerNumber: 5,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['B4'],
        instructionText: 'Repaso mezclado — identifica: Si (B)',
        displayName: 'Si',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['F3'],
        instructionText: 'Repaso mezclado — identifica con la izquierda: Fa (F)',
        displayName: 'Fa',
        fingerNumber: 2,
        hand: 'left',
      },
      {
        kind: 'note',
        expectedNotes: ['A4'],
        instructionText: 'Repaso mezclado — identifica: La (A)',
        displayName: 'La',
        hand: 'right',
      },
      {
        kind: 'note',
        expectedNotes: ['D3'],
        instructionText: 'Repaso mezclado — identifica con la izquierda: Re (D)',
        displayName: 'Re',
        fingerNumber: 4,
        hand: 'left',
      },
    ],
  },
  {
    id: 'lvl-1-melodia',
    title: 'curriculum.lvl1Melodia.title',
    subtitle: 'curriculum.lvl1Melodia.subtitle',
    role: 'melodia',
    steps: [
      { kind: 'note', expectedNotes: ['G4'], instructionText: 'Primera nota: Sol', displayName: 'Sol', hand: 'right' },
      { kind: 'note', expectedNotes: ['C5'], instructionText: 'Sube a Do', displayName: 'Do', hand: 'right' },
      { kind: 'note', expectedNotes: ['E5'], instructionText: 'Sube a Mi', displayName: 'Mi', hand: 'right' },
      { kind: 'note', expectedNotes: ['D5'], instructionText: 'Baja a Re', displayName: 'Re', hand: 'right' },
      { kind: 'note', expectedNotes: ['C5'], instructionText: 'Baja a Do', displayName: 'Do', hand: 'right' },
      { kind: 'note', expectedNotes: ['A4'], instructionText: 'Baja a La', displayName: 'La', hand: 'right' },
      { kind: 'note', expectedNotes: ['G4'], instructionText: 'Baja a Sol', displayName: 'Sol', hand: 'right' },
      { kind: 'note', expectedNotes: ['E4'], instructionText: 'Termina en Mi', displayName: 'Mi', hand: 'right' },
    ],
  },
  {
    id: 'lvl-2a-teoria-acordes',
    title: 'curriculum.lvl2Teoria.title',
    subtitle: 'curriculum.lvl2Teoria.subtitle',
    role: 'acordes',
    steps: [
      {
        kind: 'info',
        expectedNotes: [],
        displayName: '¿Qué es un acorde?',
        instructionText:
          'Un acorde es un grupo de 3 o más notas que suenan juntas y forman un color armónico. En vez de tocar una melodía nota por nota, con acordes puedes acompañar una canción completa — es la base para tocar de oído en la iglesia.',
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Cómo se forma una triada',
        instructionText:
          'La triada más simple se arma así: tomas una nota fundamental, saltas una tecla blanca para la tercera, y saltas otra para la quinta. Desde Do: Do (fundamental) → Mi (tercera) → Sol (quinta).',
        illustration: { kind: 'keyboard', highlightNotes: ['C4', 'E4', 'G4'] },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Los 4 acordes de este nivel',
        instructionText:
          'Vas a aprender Do mayor (Do-Mi-Sol), Sol mayor (Sol-Si-Re), Fa mayor (Fa-La-Do) y La menor (La-Do-Mi). Los mayores suenan brillantes; el menor suena más melancólico — misma fórmula, pero con la tercera un semitono más abajo.',
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: 'Primero, en bloque',
        instructionText:
          'En la práctica vas a tocar primero las 3 notas de cada acorde juntas, al mismo tiempo, con una mano — así es como sonará cuando acompañes de verdad. Esa parte usa el teclado táctil, porque el micrófono no puede escuchar varias notas a la vez.',
        illustration: { kind: 'keyboard', highlightNotes: ['C4', 'E4', 'G4'] },
      },
      {
        kind: 'info',
        expectedNotes: [],
        displayName: '¿Qué es arpegiar?',
        instructionText:
          'Arpegiar es tocar las notas de un acorde una por una en vez de todas juntas — como "desenrollar" el acorde. Es una técnica real que vas a usar para intros y rellenos, y también es la única forma en que el micrófono del teléfono puede reconocer un acorde: solo escucha una nota a la vez, así que si las tocas por separado las va acumulando hasta reconocer el acorde completo. Esa es la segunda parte de la práctica.',
      },
    ],
  },
  {
    id: 'lvl-2b-practica-acordes',
    title: 'curriculum.lvl2Practica.title',
    subtitle: 'curriculum.lvl2Practica.subtitle',
    role: 'acordes',
    steps: [
      {
        kind: 'chord',
        expectedNotes: ['C4', 'E4', 'G4'],
        instructionText: 'Toca las 3 notas juntas: Do, Mi, Sol',
        displayName: 'Do mayor',
        recommendedMode: 'teclado',
      },
      {
        kind: 'chord',
        expectedNotes: ['G3', 'B3', 'D4'],
        instructionText: 'Toca las 3 notas juntas: Sol, Si, Re',
        displayName: 'Sol mayor',
        recommendedMode: 'teclado',
      },
      {
        kind: 'chord',
        expectedNotes: ['F3', 'A3', 'C4'],
        instructionText: 'Toca las 3 notas juntas: Fa, La, Do',
        displayName: 'Fa mayor',
        recommendedMode: 'teclado',
      },
      {
        kind: 'chord',
        expectedNotes: ['A3', 'C4', 'E4'],
        instructionText: 'Toca las 3 notas juntas: La, Do, Mi',
        displayName: 'La menor',
        recommendedMode: 'teclado',
      },
      {
        kind: 'chord',
        expectedNotes: ['C4', 'E4', 'G4'],
        instructionText: 'Arpegia: Do, luego Mi, luego Sol, una por una',
        displayName: 'Do mayor',
        recommendedMode: 'microfono',
      },
      {
        kind: 'chord',
        expectedNotes: ['G3', 'B3', 'D4'],
        instructionText: 'Arpegia: Sol, luego Si, luego Re, una por una',
        displayName: 'Sol mayor',
        recommendedMode: 'microfono',
      },
      {
        kind: 'chord',
        expectedNotes: ['F3', 'A3', 'C4'],
        instructionText: 'Arpegia: Fa, luego La, luego Do, una por una',
        displayName: 'Fa mayor',
        recommendedMode: 'microfono',
      },
      {
        kind: 'chord',
        expectedNotes: ['A3', 'C4', 'E4'],
        instructionText: 'Arpegia: La, luego Do, luego Mi, una por una',
        displayName: 'La menor',
        recommendedMode: 'microfono',
      },
    ],
  },
  {
    id: 'lvl-3-inversiones',
    title: 'curriculum.lvl3.title',
    subtitle: 'curriculum.lvl3.subtitle',
    role: 'acordes',
    steps: [],
  },
  {
    id: 'lvl-4-progresiones',
    title: 'curriculum.lvl4.title',
    subtitle: 'curriculum.lvl4.subtitle',
    role: 'acompanamiento',
    steps: [],
  },
];

export const sampleSongs: Song[] = [
  {
    id: 'song-sublime-gracia',
    title: 'curriculum.songSublimeGracia',
    source: 'dominio_publico',
    licenseStatus: 'pendiente_revision_humana',
    licenseInfo:
      'Melodía e himno de dominio público (Amazing Grace); arreglo específico pendiente de confirmación por un humano antes de publicar.',
    levelIds: ['lvl-1-melodia', 'lvl-2b-practica-acordes'],
  },
];

// Progreso inicial de un usuario nuevo: nada completado todavía, empieza en
// Fundamentos. (Antes arrancaba en "Acordes básicos" por datos de ejemplo
// que simulaban progreso ya avanzado — confuso para una primera prueba real.)
export const sampleUserProgress: UserProgress = {
  completedLevelIds: [],
  currentStreak: 0,
  lastPracticeDate: null,
  chordsLearned: [],
  stepProgress: {},
};
